import type { Metadata } from "next";
import { DM_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";
import LenisProvider from "./LenisProvider";

const dm_sans = DM_Sans({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lora",
  display: "swap",
});





   
export const metadata: Metadata = {
  title: "ESCALIDIZZY",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};




export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${dm_sans.variable}
          antialiased
        `}
      >
        <Navbar />
        <LenisProvider>{children}</LenisProvider>
        <Footer />
      </body>
    </html>
  );
}
