import type { Metadata } from "next";
import { Lora, Orbitron, Sofia_Sans, Montserrat} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Footer from "@/components/Footer";

const lora = Lora({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-lora",
  display: "swap",
});

const lobsterX = Orbitron({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-berkshire",
});

const sofia = Sofia_Sans({
  subsets: ["latin"],
  weight: ["400"],
  variable: "--font-sofia",
  display: "swap",
});


const montserrat = Montserrat ({
  variable: "--font-montserrat",
  weight: ["700"],
});

   
export const metadata: Metadata = {
  title: "ESCALIDIZZY",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};




export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`
          ${lora.variable}
          ${lobsterX.variable}
          ${sofia.variable}
          ${montserrat.variable}
          antialiased
        `}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
